export enum Background {
  cover = "bg-cover",
  contain = "bg-contain",
  bottom = "bg-bottom",
  top = "bg-top",
  center = "bg-center",
  left = "bg-left",
  leftbottom = "bg-left-bottom",
  right = "bg-right",
  rightbottom = "bg-right-bottom",
  righttop = "bg-right-top",
  fixed = "bg-fixed",
  local = "bg-local",
  scroll = "bg-scroll",
  norepeat = "bg-no-repeat",
  repeat = "bg-repeat",
  repeatx = "bg-repeat-x",
  repeaty = "bg-repeat-y",
  repeatround = "bg-repeat-round",
  repeatspace = "bg-repeat-space",
  opacity0 = "bg-opacity-0",
  opacity25 = "bg-opacity-25",
  opacity50 = "bg-opacity-50",
  opacity75 = "bg-opacity-75",
  opacity100 = "bg-opacity-100",
  dividey_0='divide-y-0',
}
